services:
  - type: web
    name: mindpilot
    env: python
    buildCommand: ./build.sh
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: OPENAI_API_KEY
        value: "80ZHjPx3qHEr2xigido1q8wF8FzGWzgkZfzwRaVZ"
    plan: free
    autoDeploy: true
    buildFilter:
      paths:
        - frontend/**
        - backend/**
    workingDir: backend
